version: "3.9"

networks:
  docker-localstack-network:
    external:
      name: docker-localstack-network

services:
  localstack:
    image: localstack/localstack:0.12.9.1
    container_name: localstack
    ports:
      - 4572:4572 # s3
      - 4575:4575 # sns
      - 4576:4576 # sqs
      - 4584:4584 # secretsmanager
    environment:
      - SERVICES=s3,sns,sqs,secretsmanager # iam,lambda
      - DATA_DIR=${DATA_DIR:-/tmp/localstack/data}
      - LAMBDA_EXECUTOR=local
      - KINESIS_ERROR_PROBABILITY=0.0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ${TMPDIR:-/tmp/localstack}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      docker-localstack-network:
        aliases:
          - s3
          - sns
          - sqs
          - secretsmanager
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: docker-localstack-db
      POSTGRES_USER: docker-localstack-user
      POSTGRES_PASSWORD: docker-localstack-password
      PGDATA: /tmp/postgres
    volumes:
      - /var/tmp/postgres:/tmp/postgres
      - ./migration-schema/postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      docker-localstack-network:
        aliases:
          - postgres
    restart: unless-stopped

#  pgadmin:
#    image: fenglc/pgadmin4:latest
#    container_name: "pgadmin"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#    depends_on:
#      - postgres
#    volumes:
#      - /var/tmp/.pgadmin:/tmp/.pgadmin
#    ports:
#      - "5050:5050"
#    restart: unless-stopped
#
#  portainer:
#    image: portainer/portainer
#    container_name: "portainer"
#    ports:
#      - "9000:9000"
#    command: --no-auth
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /var/tmp:/data
#    restart: unless-stopped