env:
  BUILDKITE_CLEAN_CHECKOUT: true
  DEV_PROFILE: 'dev'
  DEV_PROFILE_AGENT: 'dev'
steps:
  - name: ':terraform: Validate'
    plugins:
      docker-compose#v3.6.0:
        config: ${INFRA_PATH:-.}/docker-compose.yaml
        pull: validate
        run: validate
    agents:
      queue: ${DEV_PROFILE_AGENT}
    env:
      INFRA_PATH: ${INFRA_PATH:-.}

  - name: ':terraform: Format'
    plugins:
      docker-compose#v3.6.0:
        config: ${INFRA_PATH:-.}/docker-compose.yaml
        pull: fmt
        run: fmt
    agents:
      queue: ${DEV_PROFILE_AGENT}
    env:
      INFRA_PATH: ${INFRA_PATH:-.}

  - name: ':terraform: Plan Dev'
    plugins:
      docker-compose#v3.6.0:
        config: ${INFRA_PATH:-.}/docker-compose.yaml
        pull: plan
        run: plan
      artifacts#v1.3.0:
        upload:
          from: ${INFRA_PATH:-.}/tf-plan-dev
          to: tf-plan-dev
    agents:
      queue: ${DEV_PROFILE_AGENT}
    env:
      ENV_PROFILE: ${DEV_PROFILE}
      INFRA_PATH: ${INFRA_PATH:-.}

  - wait: ~

  - block: ':terraform: Apply changes on Dev?'

  - name: ':terraform: Applying changes on Dev'
    plugins:
      docker-compose#v3.6.0:
        config: ${INFRA_PATH:-.}/docker-compose.yaml
        pull: apply
        run: apply
      artifacts#v1.3.0:
        upload:
          from: tf-plan-dev
          to: ${INFRA_PATH:-.}/tf-plan-dev
    agents:
      queue: ${DEV_PROFILE_AGENT}
    env:
      ENV_PROFILE: ${DEV_PROFILE}
      INFRA_PATH: ${INFRA_PATH:-.}
