env:
  BUILDKITE_CLEAN_CHECKOUT: true

  PROFILE_DEV: 'dev'

  BK_AGENT_INFRA: 'infra'
steps:
  - label: ':terraform: Validate'
    plugins:
      docker-compose#v3.6.0:
        config: ${INFRA_PATH:-.}/docker-compose.yaml
        pull: validate
        run: validate
    agents:
      queue: ${BK_AGENT_INFRA}
    env:
      INFRA_PATH: ${INFRA_PATH:-.}

  - label: ':terraform: Format'
    plugins:
      docker-compose#v3.6.0:
        config: ${INFRA_PATH:-.}/docker-compose.yaml
        pull: fmt
        run: fmt
    agents:
      queue: ${BK_AGENT_INFRA}
    env:
      INFRA_PATH: ${INFRA_PATH:-.}

  - label: ':terraform: Plan Dev'
    plugins:
      docker-compose#v3.6.0:
        config: ${INFRA_PATH:-.}/docker-compose.yaml
        pull: plan
        run: plan
      artifacts#v1.3.0:
        upload:
          from: ${INFRA_PATH:-.}/tf-plan-dev
          to: tf-plan-dev
    agents:
      queue: ${BK_AGENT_INFRA}
    env:
      PROFILE: ${PROFILE_DEV}
      INFRA_PATH: ${INFRA_PATH:-.}

  - wait: ~

  - block: ':terraform: Apply changes on Dev?'

  - label: ':terraform: Applying changes on Dev'
    plugins:
      docker-compose#v3.6.0:
        config: ${INFRA_PATH:-.}/docker-compose.yaml
        pull: apply
        run: apply
      artifacts#v1.3.0:
        upload:
          from: tf-plan-dev
          to: ${INFRA_PATH:-.}/tf-plan-dev
    agents:
      queue: ${BK_AGENT_INFRA}
    env:
      PROFILE: ${PROFILE_DEV}
      INFRA_PATH: ${INFRA_PATH:-.}
