env:
  BUILDKITE_CLEAN_CHECKOUT: true

  AWS_ACTION_ROTATE_SECRETS: 'rotate-secrets'

  AWS_IAM_ROLE_DEV: "arn:aws:iam::123456789012:role/AwsManagementRole"

  BK_AGENT_DEVOPS: 'dev-aws-ops'
steps:
  - block: ':aws: DevOps'
    fields:
      - select: 'Select operation'
        options:
          - label: 'Rotate secrets'
            value: ${AWS_ACTION_ROTATE_SECRETS}
        key: AWS_ACTION
        required: true
      - select: 'Select environment'
        options:
          - label: 'Development'
            value: ${AWS_IAM_ROLE_DEV}
        key: AWS_IAM_ROLE
        required: true
      - text: 'Reason?'
        key: BK_ACTION_REASON
        required: true
  
  - label: ':aws: DevOps Apply'
    branches: 'main'
    command: '.buildkite/scripts/aws-ops.sh'
    agents:
      queue: ${BK_AGENT_DEVOPS}
      
  - label: ':buildkite: Annotate build'
    branches: 'main'
    command: '.buildkite/scripts/bk-annotate.sh'
    agents:
      queue: ${BK_AGENT_DEVOPS}
