env:
  BUILDKITE_CLEAN_CHECKOUT: true

  BK_PIPELINE_TEMPLATE_DYNAMO_DELETE_ALL_ITEMS: 'aws-dynamodb-delete-items-pipeline'
  AWS_IAM_ACCOUNT_DEV: '123456789012'
  AWS_IAM_ACCOUNT_PRD: 'unsupported'
  PROFILE_DEV: 'dev'
  PROFILE_PRD: 'prd'
  BK_AGENT_DEV: 'dev-aws-ops'
  BK_AGENT_PRD: 'prd-aws-ops'

  BK_AGENT_DEVOPS: 'dev-aws-ops'
steps:
  - block: ':aws: AWS DevOps development'
    fields:
      - select: ':aws: Target Environment'
        key: PROFILE
        default: ${PROFILE_DEV}
        hint: ':aws: AWS target environment'
        options:
          - label: 'Development'
            value: ${PROFILE_DEV}
        required: true
      - select: ':docker: Application'
        key: AWS_APP
        default: 'docker-localstack'
        hint: ':docker: Affected application'
        options:
          - label: 'Docker localstack test application'
            value: 'docker-localstack'
        required: true
      - select: ':buildkite: Select operation'
        key: TEMPLATE_NAME
        options:
          - label: ':aws: :dynamodb: AWS dynamodb delete all items'
            value: ${BK_PIPELINE_TEMPLATE_DYNAMO_DELETE_ALL_ITEMS}
        required: true
      - text: 'Reason?'
        key: BK_ACTION_REASON
        required: true

  - label: ':buildkite: Create pipeline'
    branches: 'main'
    command: '.buildkite/scripts/bk-create-pipeline.sh | buildkite-agent pipeline upload'
    agents:
      queue: ${BK_AGENT_DEVOPS}
    env:
      AWS_IAM_ACCOUNT_DEV: ${AWS_IAM_ACCOUNT_DEV}
      AWS_IAM_ACCOUNT_PRD: ${AWS_IAM_ACCOUNT_PRD}
      PROFILE_DEV: ${PROFILE_DEV}
      PROFILE_PRD: ${PROFILE_PRD}
      BK_AGENT_DEV: ${BK_AGENT_DEV}
      BK_AGENT_PRD: ${BK_AGENT_PRD}

  - label: ':buildkite: Annotate build'
    branches: 'main'
    command: '.buildkite/scripts/bk-annotate.sh'
    agents:
      queue: ${BK_AGENT_DEVOPS}
