env:
  BUILDKITE_CLEAN_CHECKOUT: true
  IMAGE_NAME: k8s-ci-cd
  IMAGE_VERSION: 1.0.${BUILDKITE_BUILD_NUMBER}

  BK_AGENT_DEVOPS: 'dev-k8s-ops'
steps:
  - label: ':k8s: :docker: Build'
    plugins:
      docker-compose#v3.5.0:
        config: .buildkite/image/docker-compose.yml
        build: k8s-ci-di
