env:
  BUILDKITE_CLEAN_CHECKOUT: true
  
  K8S_ACTION_START: 'start'
  K8S_ACTION_STOP: 'stop'

  AWS_IAM_ACCOUNT_DEV: 'AWS_IAM_ACCOUNT_DEV'

  BK_AGENT_DEVOPS: 'dev-k8s-ops'
steps:
  - block: ':k8s: DevOps'
#    branches: "main"
    fields:
      - select: 'Select operation'
        options:
          - label: 'Start'
            value: ${K8S_ACTION_START}
          - label: 'Stop'
            value: ${K8S_ACTION_STOP}
        key: K8S_ACTION
        requires: true
      - select: 'Select environment'
        options:
          - label: 'Development'
            value: ${AWS_IAM_ACCOUNT_DEV}
        key: AWS_IAM_ACCOUNT
        requires: true
      - text: 'Reason?'
        key: BK_ACTION_REASON
        required: true

  - label: ':k8s: Starting action'
    command: '.buildkite/scripts/k8s-ops.sh'
    agents:
      queue: ${BK_AGENT_DEVOPS}

  - label: ':buildkite: Annotate build'
    #    branches: 'main'
    command: '.buildkite/scripts/bk-annotate.sh'
    agents:
      queue: ${BK_AGENT_DEVOPS}
