apiVersion: v1
kind: Service
metadata:
  name: docker-localstack
  labels:
    app: docker-localstack
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
    - port: 8443
      name: https
  selector:
    app: docker-localstack