apiVersion: v1
kind: Service
metadata:
  name: docker-localstack-lb
spec:
  selector:
    app: docker-localstack
  ports:
    - protocol: "TCP"
      port: 8443
      name: https
  type: LoadBalancer
