apiVersion: v1
kind: Service
metadata:
  name: docker-localstack-webapp
spec:
  selector:
    app: docker-localstack-webapp
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
