apiVersion: v1
kind: Service
metadata:
  name: docker-localstack-webapp-lb
spec:
  selector:
    app: docker-localstack-webapp
  ports:
    - protocol: "TCP"
      port: 8080
      name: http
    - protocol: "TCP"
      port: 8443
      name: https
  type: LoadBalancer
