spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/docker-localstack-db
    username: docker-localstack-user
    password: docker-localstack-password
