spring:
  datasource:
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    url: create1st/docker_localstack_db/docker_localstack
    username: ${spring.datasource.url}
