server:
  port: 8080

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    aws:
      secret: craftandtechnology/docker_localstack_db/docker_localstack

cloud:
  aws:
    region:
      static: ${AWS_DEFAULT_REGION:-us-east-1}
    account:
      id: ${ACCOUNT_ID}
    kms:
      endpoint: http://localstack:4566
      alias: alias/docker-localstack-kms-key
    sns:
      endpoint: http://localstack:4566
    sqs:
      endpoint: http://localstack:4566
    secretsmanager:
      endpoint: http://localstack:4566
    dynamodb:
      endpoint: http://localstack:4566

