application:
  rest:
    cors:
      access-control-allow-origin: http://localhost:3000

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/docker-localstack-db
    aws:
      secret: craftandtechnology/docker_localstack_db/docker_localstack
cloud:
  aws:
    region:
      static: ${AWS_DEFAULT_REGION:-us-east-1}
    account:
      id: ${ACCOUNT_ID}
    kms:
      endpoint: http://localhost:4566
      alias: alias/docker-localstack-kms-key
    sns:
      endpoint: http://localhost:4566
    sqs:
      endpoint: http://localhost:4566
    secretsmanager:
      endpoint: http://localhost:4566
    dynamodb:
      endpoint: http://localhost:4566
