spring:
  datasource:
    driverClassName: org.postgresql.Driver
    aws:
      secret: craftandtechnology/docker_localstack_db/docker_localstack
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://craftandtechnology.au.auth0.com/
          jwk-set-uri: https://craftandtechnology.au.auth0.com/.well-known/jwks.json
cloud:
  aws:
    region:
      static: ${AWS_DEFAULT_REGION}
    account:
      id: ${ACCOUNT_ID}
    kms:
      endpoint: https://kms.${AWS_DEFAULT_REGION}.amazonaws.com
      alias: alias/docker-localstack-kms-key
    sns:
      endpoint: https://sns.${AWS_DEFAULT_REGION}.amazonaws.com
    sqs:
      endpoint: https://sqs.${AWS_DEFAULT_REGION}.amazonaws.com
    secretsmanager:
      endpoint: http://sqs.${AWS_DEFAULT_REGION}.amazonaws.com
    dynamodb:
      endpoint: https://dynamodb.${AWS_DEFAULT_REGION}.amazonaws.com
