version: '3.8'

services:

  apply:
    image: ${IMAGE_NAME:-k8s-ci-cd}:${IMAGE_VERSION:-local-snapshot}
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials
      - AWS_SESSION_TOKEN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - K8S_CLUSTER_NAME
      - K8S_NAMESPACE
      - PROFILE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker:/root/.docker:ro
      - ${HOME}/.aws:/root/.aws:ro
      - ${PWD}/.buildkite/scripts:/root/scripts
    working_dir: /root/scripts
    entrypoint: ./k8s-${K8S_ACTION}.sh
