version: "3.9"

networks:
  docker-localstack-network:
    external:
      name: docker-localstack-network

services:
  validate:
    image: hashicorp/terraform:0.14.8
    environment:
      - SSH_AUTH_SOCK
      - GIT_SSH_COMMAND=ssh -o GlobalKnownHostsFile=/known_hosts
      - TF_INPUT=0
      - TF_PATH=${INFRA_PATH:-.}/terraform
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
      - $HOME/.ssh/known_hosts:/known_hosts
      - $PWD:/working_dir
    working_dir: /working_dir
    entrypoint: sh
    command: -c ". ${INFRA_PATH:-.}/scripts/validate.sh"

  fmt:
    image: hashicorp/terraform:0.14.8
    environment:
      - SSH_AUTH_SOCK
      - GIT_SSH_COMMAND=ssh -o GlobalKnownHostsFile=/known_hosts
      - TF_INPUT=0
      - TF_PATH=${INFRA_PATH:-.}/terraform
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
      - $HOME/.ssh/known_hosts:/known_hosts
      - $PWD:/working_dir
    working_dir: /working_dir
    entrypoint: sh
    command: -c ". ${INFRA_PATH:-.}/scripts/fmt.sh"

  plan:
    image: hashicorp/terraform:0.14.8
    environment:
      - SSH_AUTH_SOCK
      - GIT_SSH_COMMAND=ssh -o GlobalKnownHostsFile=/known_hosts
      - TF_INPUT=0
      - TF_PATH=${INFRA_PATH:-.}/terraform
      - PROFILE=${PROFILE:-dev}
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
      - $HOME/.ssh/known_hosts:/known_hosts
      - $PWD:/working_dir
    working_dir: /working_dir
    entrypoint: sh
    command: -c ". ${INFRA_PATH:-.}/scripts/plan.sh"
    networks:
      - docker-localstack-network

  apply:
    image: hashicorp/terraform:0.14.8
    environment:
      - SSH_AUTH_SOCK
      - GIT_SSH_COMMAND=ssh -o GlobalKnownHostsFile=/known_hosts
      - TF_INPUT=0
      - TF_PATH=${INFRA_PATH:-.}/terraform
      - PROFILE=${PROFILE:-dev}
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
      - $HOME/.ssh/known_hosts:/known_hosts
      - $PWD:/working_dir
    working_dir: /working_dir
    entrypoint: sh
    command: -c ". ${INFRA_PATH:-.}/scripts/apply.sh"
    networks:
      - docker-localstack-network