apiVersion: v1
kind: Config
preferences: {}

clusters:
{{- range .Values.eksInstances }}
- cluster:
    server: {{ .server }}
    insecure-skip-tls-verify: true
  name: {{ .contextName }}
{{- end }}

users:
{{- range .Values.eksInstances }}
- name: {{ .userName }}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "{{ .contextName }}"
{{- end }}

contexts:
{{- range .Values.eksInstances }}
- context:
    cluster: {{ .contextName }}
    user: {{ .userName }}
  name: {{ .userName }}
{{- end }}