env:
  BUILDKITE_CLEAN_CHECKOUT: true
  IMAGE_NAME: docker-app
  IMAGE_VERSION: 1.0.${BUILDKITE_BUILD_NUMBER}

  PROFILE_DEV: 'dev'

  BK_AGENT_INFRA: 'app'
steps:
  - label: ':gradle: :kotlin: Build'
    plugins:
      - thedyrt/change-directory#v0.1.1:
          cd: app
    command: './gradlew clean build -x test -x integrationTest'

  - label: ':gradle: :kotlin: :junit: Test'
    plugins:
      - thedyrt/change-directory#v0.1.1:
          cd: app
    command: './gradlew clean test -x integrationTest'

  - label: ':gradle: :kotlin: :junit: Integration Test'
    plugins:
      - thedyrt/change-directory#v0.1.1:
          cd: app
    command: './gradlew clean integrationTest -x test'