env:
  BUILDKITE_CLEAN_CHECKOUT: true
  IMAGE_NAME: docker-app
  IMAGE_VERSION: 1.0.${BUILDKITE_BUILD_NUMBER}
  GRADLE_CACHE: /tmp/docker-localstack/${BUILDKITE_BUILD_NUMBER}

  PROFILE_DEV: 'dev'

  BK_AGENT_INFRA: 'app'
steps:
  - label: ':gradle: :kotlin: Build'
    plugins:
      - thedyrt/change-directory#v0.1.1:
          cd: app
    command: './gradlew clean build -x test -x integrationTest'

  - label: ':gradle: :kotlin: :junit: Test'
    plugins:
      - thedyrt/change-directory#v0.1.1:
          cd: app
    command: './gradlew clean test -x integrationTest'

  - label: ':gradle: :kotlin: :junit: Integration Test'
    plugins:
      docker-compose#v3.5.0:
        config: app/docker-compose-integration-tests.yml
        run: integration-test
        env:
          - GRADLE_CACHE