version: '3.8'

networks:
  docker-localstack-network:

services:

  web-build:
    build:
      context: .
      dockerfile: image/Dockerfile
    image: ${IMAGE_NAME:-docker-localstack-webapp}:${IMAGE_VERSION:-local-snapshot}
    container_name: webapp
    networks:
      - docker-localstack-network
