env:
  BUILDKITE_CLEAN_CHECKOUT: true

  AWS_IAM_ROLE: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/AwsManagementRole"
steps:
  - label: ':aws: :dynamodb: Rotating secrets in ${PROFILE_NAME}'
    branches: 'main'
    command: '.buildkite/scripts/aws-secrets-manager-rotate-secrets.sh ${ESC_DOLLAR}{AWS_IAM_ROLE}'
    agents:
      queue: '${BK_AGENT}'
